### ISSUE TITLE
Is this still maintained? How about syncing it to the upstream hg repo?

### ISSUE THREAD

**Issue by lenucksi** [gajim/gajim#1]

**Comment by guilhem** [comment]
No it's definitively not maintain and have never be.

I created this repo to being able to use auto git -> bzr on launchpad (and crete deb packages) and to prove it's possible to use import hg to git.

I can give this repo to core team when they will understand that hg is really dead now :)

If you want to do this yourself, I will be happy to give you rights on repo :)

**Comment by lenucksi** [comment]
Thank you for your answer.
I've talked to people in the Gajim channel and they at least aggreed to having a synced Git mirror and wondered if issue sync would be an option.

Thus I'd happy to take your offer to give me rights on the repo.
Since Gajim also provides other repos such as python-nbxmpp I would also appreciate rights to access the gajim organisation part, so I can create another mirror for the bespoke other repo.

**Comment by guilhem** [comment]
Welcome @lenucksi :) you are owner.

With great power comes great responsability
